language: rust
rust:
  - stable
  - beta
  - nightly
sudo: required
dist: trusty
cache: cargo
branches:
  only:
    - master
# Needed for codecov reporting
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev
      - libssl-dev
before_script:
  - cargo install --force cargo-audit
script:
  - cargo test -- --test-threads=1
  - cargo test --example google
  - cargo audit
after_success: |
  RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin &&
  cargo tarpaulin --out Xml &&
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"
notifications:
  email:
    on_success: never
