[package]
name = "openidconnect"
version = "1.0.0-alpha.1"
authors = ["David A. Ramos <ramos@cs.stanford.edu>"]
description = "OpenID Connect library"
license = "MIT"
repository = "https://github.com/ramosbugs/openidconnect-rs"

[features]
nightly = []

[dependencies]
base64 = "0.9"
chrono = "0.4"
failure = "0.1"
failure_derive = "0.1"
futures = "0.1"
http = "0.1"
itertools = "0.7.8"
log = "0.4"
oauth2 = "3.0.0-alpha.3"
rand = "0.6"
retry = "0.5"
ring = "0.14"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
untrusted = "0.6"
url = "1.0"

[dev-dependencies]
color-backtrace = { version = "0.2" }
env_logger = "0.5"
hyper = "0.11"
pretty_assertions = "0.5"
reqwest = "0.9"
